apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: 657907747545.dkr.ecr.us-east-1.amazonaws.com/ec2-monitoring:latest
        ports:
        - containerPort: 5000
